# Generated by Django 5.2.7 on 2025-11-11 14:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pozuuv.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
