# Generated by Django 5.2.7 on 2025-11-12 15:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_for_users_hpwnzn', max_length=255, null=True, verbose_name='image'),
        ),
    ]
