# Generated by Django 5.2.7 on 2025-11-12 15:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_for_cover_r4fftg', max_length=255, null=True, verbose_name='event_image'),
        ),
    ]
