# Generated by Django 5.2.7 on 2025-12-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='Seminar', max_length=200),
            preserve_default=False,
        ),
    ]
