# Generated by Django 5.2.12 on 2026-03-18 12:12

import cloudinary.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('cover_img', cloudinary.models.CloudinaryField(blank=True, default='default_for_cover_r4fftg', max_length=255, null=True, verbose_name='image')),
                ('discription', models.TextField()),
                ('heading_01', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_01', models.TextField(blank=True, null=True)),
                ('heading_02', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_02', models.TextField(blank=True, null=True)),
                ('heading_03', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_03', models.TextField(blank=True, null=True)),
                ('heading_04', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_04', models.TextField(blank=True, null=True)),
                ('heading_05', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_05', models.TextField(blank=True, null=True)),
                ('heading_06', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_06', models.TextField(blank=True, null=True)),
                ('heading_07', models.CharField(blank=True, max_length=200, null=True)),
                ('paragraph_07', models.TextField(blank=True, null=True)),
                ('quoter', models.CharField(blank=True, max_length=200, null=True)),
                ('quotes', models.TextField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('sub_title', models.TextField(blank=True, null=True)),
                ('cover_img', cloudinary.models.CloudinaryField(blank=True, default='default_for_cover_r4fftg', max_length=255, null=True, verbose_name='image')),
                ('discription', models.TextField()),
                ('outcomes', models.TextField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
