# Generated by Django 5.2.7 on 2025-11-11 14:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_for_blogs_aqpckm.png', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='cover_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_for_blogs_aqpckm.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
