# Generated by Django 5.2.7 on 2025-11-12 15:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0004_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_for_cover_r4fftg', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='cover_img',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_for_cover_r4fftg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
