# Generated by Django 5.2.7 on 2025-12-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0005_alter_article_cover_img_alter_magazine_cover_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='heading_01',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='heading_02',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='heading_03',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph_01',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph_02',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph_03',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='quoter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='quotes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.CharField(default='10min', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='read_time',
            field=models.CharField(default='48min', max_length=100),
            preserve_default=False,
        ),
    ]
