# Generated by Django 5.2.7 on 2026-02-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0006_article_heading_01_article_heading_02_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='heading_04',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='heading_05',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='heading_06',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='heading_07',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph_04',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph_05',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph_06',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph_07',
            field=models.TextField(blank=True, null=True),
        ),
    ]
