# Generated by Django 5.2.7 on 2026-03-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0007_article_heading_04_article_heading_05_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='magazine',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
        ),
    ]
